name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest-mo

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/litholicht-konfigurator || git clone https://git.tecmaxx.de/mamotec/litholicht-konfigurator.git /opt/litholicht-konfigurator
            cd /opt/litholicht-konfigurator
            git pull origin main
            docker compose down || true
            docker compose up -d --build
